stages:
  - maven-build
  - docker-build
  - docker-push
cache:
  paths:
    - .m2/repository

maven-build:
  stage: maven-build
  tags: 
    - local
  image: maven:latest
  script:
    - mvn clean package -B -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

docker-build:
  stage: docker-build
  tags: 
    - local
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest .
   # - docker tag ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${CI_COMMIT_SHA} ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest
  only:
    - main

docker-push:
  stage: docker-push
  tags: 
    - local
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    #- docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest
  only:
    - main