version: '3.8'

services:
  app:
    build: .
    ports:
      - "8005:8005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/leave-tracker-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Shiva@12
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Shiva@12
      - MYSQL_DATABASE=leave-tracker-db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: