apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: leave-tracker
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ .Values.database.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
